apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: tf-test-pipeline
serialPipeline:
  stages:
    - targetId: tf-plan
    - targetId: tf-deploy

---

apiVersion: deploy.cloud.google.com/v1
kind: CustomTargetType
metadata:
  name: tf
customActions:
  renderAction: custom-render
  deployAction: custom-deploy
